name: pdf_combine
description: "PDF Combine - Combine multiple PDF files into one with page selection"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  pdfrx:
    path: ../../

  file_selector: ^1.0.3
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  animated_reorderable_list: ^1.3.0
  web: ^1.1.1
  desktop_drop: ^0.7.0
  jpeg_encode: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
