name: pdfrx_example
description: "Demonstrates how to use the pdfrx plugin."
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  pdfrx:
    path: ../../
  pdfrx_wasm:
    path: ../../wasm/pdfrx_wasm/

  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  synchronized: ^3.3.1
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
