name: pdfrx_engine
description: pdfrx_engine is a PDF rendering and manipulation API built on top of PDFium, designed to be used with the pdfrx plugin. Supports viewing, editing, and combining PDF documents.
version: 0.3.7
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx/tree/master/packages/pdfrx_engine
issue_tracker: https://github.com/espresso3389/pdfrx/issues

environment:
  sdk: ^3.9.0
resolution: workspace

# Some of the dependencies are intentionally not pinned to a specific version
# to allow for more flexibility in resolving versions when used in larger projects.
dependencies:
  pdfium_dart: ^0.1.2
  collection:
  crypto: ^3.0.6
  ffi:
  http:
  path:
  rxdart:
  synchronized: ^3.4.0
  vector_math: ^2.2.0
  archive: ^4.0.7
  image: ^4.5.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2


