name: pdfrx_coregraphics
description: CoreGraphics-backed Pdfrx engine layer for Apple platforms.
version: 0.1.9
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx/tree/master/packages/pdfrx
issue_tracker: https://github.com/espresso3389/pdfrx/issues

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.29.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  pdfrx_engine: ^0.3.4
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PdfrxCoregraphicsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: PdfrxCoregraphicsPlugin
        sharedDarwinSource: true
