name: pdfium_dart
description: Dart FFI bindings for PDFium library. Provides low-level access to PDFium's C API from Dart.
version: 0.1.3
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx/tree/master/packages/pdfium_dart
issue_tracker: https://github.com/espresso3389/pdfrx/issues

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  archive: ^4.0.7
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  http: ^1.5.0
  native_toolchain_c: ^0.17.4
  path: ^1.9.1

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.26.2
