name: pdfrx
description: pdfrx is a rich and fast PDF viewer implementation built on the top of PDFium. The plugin supports Android, iOS, Windows, macOS, Linux, and Web.
version: 2.2.3
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx/tree/master/packages/pdfrx
issue_tracker: https://github.com/espresso3389/pdfrx/issues
screenshots:
  - description: 'Viewer example on Web'
    path: screenshot.jpg

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.29.0"
resolution: workspace

dependencies:
  pdfrx_engine: ^0.2.0
  collection:
  crypto: ^3.0.6
  dart_pubspec_licenses: ^3.0.12
  ffi:
  flutter:
    sdk: flutter
  http:
  path:
  path_provider: ^2.1.5
  rxdart:
  synchronized: ^3.4.0
  url_launcher: ^6.3.2
  vector_math: ^2.2.0
  web: ^1.1.1

dev_dependencies:
  ffigen: ^19.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  archive: ^4.0.7

executables:
  remove_wasm_modules:
  remove_darwin_pdfium_modules:

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        pluginClass: PdfrxPlugin
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        pluginClass: PdfrxPlugin
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true
      web:

  assets:
    - assets/

