name: Pana Analysis

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
  workflow_dispatch:

jobs:
  pana:
    name: Run pana analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package_name: pdfrx_engine
            package_path: packages/pdfrx_engine
          - package_name: pdfrx
            package_path: packages/pdfrx
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y webp

      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 --branch stable ~/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          ~/flutter/bin/flutter config --no-enable-android --no-enable-linux-desktop
          ~/flutter/bin/flutter channel stable
          ~/flutter/bin/flutter doctor -v

      - name: Pub get (workspace)
        run: flutter pub get

      - name: Activate pana
        run: |
          dart pub global activate pana
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Run pana (${{ matrix.package_name }})
        working-directory: ${{ matrix.package_path }}
        run: ~/.pub-cache/bin/pana --json --no-warning --exit-code-threshold 0 | jq -e '.tags | any(. == "is:wasm-ready")'
